### ISSUE TITLE
Outline player attacks tree

### ISSUE THREAD

**Issue by kgwong** [kgwong/Project-Inferno#19]

**Comment by blahred** [comment]
I placed it alongside the pictures of the player attacks.

**Comment by kgwong** [comment]
So the second attack is always the same? How does the first attack follow through into the second attack?

**Comment by blahred** [comment]
Each combo will have a first attack and second attack. There will be three ways of attacking: high, medium, low. The first of each set will always be the same but different from the second of each set. After the second attack of the combo, the attack modes will reset. 
So say you do a high, high, medium, low attack. According to the mapping it will go X1X2 Y1Z2
X-High 
Y- Medium
Z- Low

**Comment by kgwong** [comment]
Ok but I meant that each 2nd (in a combo) X is an upward lunge, every 2nd Y is a forward lunge, and every 2nd Z is an upward slash? 

Also, what is the animation transition from the first attack to the second attack? In real life (well, idk) a swordsman would have to follow through his attack from his first. 

Animation wise, how does the player go from an downward strike, to a lunge? 
How does the player go from a sideways slash to a lunge?
etc, etc? Does the player spin around during some animations, etc....

**Comment by blahred** [comment]
First part: Yes

Second part: There will be a full animation for each of the separate attacks. Each different attack will be first completed before the next action is taken. The thing that makes each combo unique however will be the extra set of frames/animations in between the different combos. I can't draw for the life of me so I will be coordinating that with Marissa personally after we get the first 6 animations. So there will be 9 "in between" animations. In total, 15 attack animations.
