### ISSUE TITLE
Decide game controls

### ISSUE THREAD

**Issue by kgwong** [kgwong/Project-Inferno#7]
Controller? Keyboard? Need all key mappings

**Comment by blahred** [comment]
xbox controller

**Comment by kgwong** [comment]
Need button mappings

**Comment by blahred** [comment]
A-Jump

Left JOYSTICK- Direction of Player's movement
Right JOYSTICK- Where the Player faces/aiming weapon

B-(tap) Back Step
B-(with direction) Roll

(Right Bumper) - Regular attack
(DOWN Right Joystick + Right Bumper)- Downside Attack
(UP Right Joystick + Right Bumper) - High Attack
(UP Left Joystick + Right Bumper) - Push 

Left Bumper- Bring up shield/Put away shield
Left Trigger- Use shield

Right Trigger- Use Bow/Hook

Left Arrow- Change consumable 
Right Arrow- Change consumable 
Up Arrow- Heal
Down Arrow- Use Consumable

START- for fucking noobs to pause the game
BACK- fucking nothing

**Comment by kgwong** [comment]
we will talk about it tuesday

**Comment by kgwong** [comment]
Reformatted with Sam's help. Approved as tentative controls
